version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: onboarding-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ob12345
    volumes:
      - ./init-mongo-onboarding.js:/docker-entrypoint-initdb.d/init-mongo-onboarding.js:ro
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ob12345
      ME_CONFIG_MONGODB_URL: mongodb://root:ob12345@mongo:27017/